#!/usr/bin/env bash

# ================================================
#  Prompt
# ================================================

source $BASHDOTDIR/scripts/git-prompt

PS1_ERROR() {
  local e=$?
  #(( e )) && printf "$e|" # BW
  (( e )) && printf "\033[01;31m[$e]\033[00m "  # color
  return $e
}

PS1='\[\e[38;5;130m\]$(__git_ps1 "[%s] ")\[\e[00m\]\[\e[38;5;51m\]\W\[\e[00m\] \[\e[38;5;$(($?==0?34:124))m\]» \[\e[0m\]'
#PROMPT_COMMAND='\[\e[38;5;130m\]$(__git_ps1 "[%s]")'
PS1='\n\[\e[00m\]\[\e[1m\]\W\[\e[00m\] \[\e[38;5;$(($?==0?29:88))m\]» \[\e[0m\]'
